# Generated by Django 4.2.1 on 2023-05-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0003_anexo_produto_ativo_restaurante_ativo_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='caminho',
        ),
        migrations.AddField(
            model_name='anexo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anexo',
            name='titulo',
            field=models.CharField(default='anexo', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_restaurante',
            field=models.CharField(default='000', max_length=10),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
