# Generated by Django 4.2.1 on 2023-05-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0004_remove_anexo_caminho_anexo_ativo_anexo_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='imagem', max_length=30)),
                ('caminho', models.ImageField(blank=True, upload_to='imagens/%Y/%m/%d/')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='anexo',
        ),
        migrations.DeleteModel(
            name='Anexo',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ManyToManyField(to='totem_cliente.imagem'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='imagem',
            field=models.ManyToManyField(to='totem_cliente.imagem'),
        ),
    ]
