# Generated by Django 4.2.1 on 2023-05-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0005_imagem_remove_produto_anexo_remove_restaurante_anexo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='imagem',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m/%d/'),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m/%d/'),
        ),
    ]
