# Generated by Django 4.2.1 on 2023-05-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0007_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='descricao', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='ingredientes',
            field=models.ManyToManyField(related_name='produtos', to='totem_cliente.ingrediente'),
        ),
    ]
