# Generated by Django 4.2.1 on 2023-05-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0008_ingrediente_produto_descricao_produto_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m/%d/'),
        ),
    ]
