# Generated by Django 4.2.1 on 2023-05-14 00:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0009_ingrediente_ativo_ingrediente_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/categorias/%Y/%m/%d/')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/combos/%Y/%m/%d/')),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='totem_cliente.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='carrinho',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_restaurante',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='logo',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='preco_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempedido',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_interno',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_hora_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(default='cliente', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/restaurantes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/ingredientes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='totem_cliente.produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/produtos/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.DeleteModel(
            name='ItemCarrinho',
        ),
        migrations.AddField(
            model_name='produtoingrediente',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem_cliente.ingrediente'),
        ),
        migrations.AddField(
            model_name='produtoingrediente',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem_cliente.produto'),
        ),
        migrations.AddField(
            model_name='combo',
            name='produtos',
            field=models.ManyToManyField(to='totem_cliente.produto'),
        ),
        migrations.AddField(
            model_name='combo',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem_cliente.restaurante'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='totem_cliente.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempedido',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='totem_cliente.combo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='totem_cliente.categoria'),
        ),
    ]
