# Generated by Django 4.2.1 on 2023-05-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0010_categoria_combo_produtoingrediente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='combo',
            name='categoria',
            field=models.ManyToManyField(to='totem_cliente.categoria'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='categoria',
            field=models.ManyToManyField(to='totem_cliente.categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ManyToManyField(to='totem_cliente.categoria'),
        ),
    ]
