# Generated by Django 4.2.1 on 2023-05-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0013_alter_combo_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('padrao', models.BooleanField(default=False)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem_cliente.combo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem_cliente.produto')),
            ],
        ),
    ]
