# Generated by Django 4.2.1 on 2023-05-14 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0014_comboproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='produtos',
        ),
    ]
