# Generated by Django 4.2.1 on 2023-05-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0015_remove_combo_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduto',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produtoingrediente',
            name='padrao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produtoingrediente',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
