# Generated by Django 4.2.1 on 2023-05-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0016_comboproduto_quantidade_produtoingrediente_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
