# Generated by Django 4.2.1 on 2023-05-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0018_categoria_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
