# Generated by Django 4.2.1 on 2023-05-16 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0019_produto_visivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtoingrediente',
            old_name='quantidade',
            new_name='quantidade_padrao',
        ),
        migrations.RemoveField(
            model_name='comboproduto',
            name='padrao',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='produtoingrediente',
            name='padrao',
        ),
        migrations.AddField(
            model_name='comboproduto',
            name='alternativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comboproduto',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='totem_cliente.restaurante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtoingrediente',
            name='quantidade_maxima',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='produtoingrediente',
            name='quantidade_minima',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='totem_cliente.combo'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='totem_cliente.produto'),
        ),
        migrations.CreateModel(
            name='ItemAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_alterada', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='totem_cliente.ingrediente')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem_cliente.itempedido')),
            ],
        ),
    ]
