# Generated by Django 4.2.1 on 2023-05-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0019_produto_visivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoParteProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('padrao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('produto_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='totem_cliente.produto')),
                ('produto_parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem_cliente.produto')),
            ],
        ),
        migrations.RemoveField(
            model_name='comboproduto',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='comboproduto',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produtoingrediente',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='produtoingrediente',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='combo',
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.DeleteModel(
            name='ComboProduto',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='ProdutoIngrediente',
        ),
    ]
