# Generated by Django 4.2.1 on 2023-05-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0020_rename_quantidade_produtoingrediente_quantidade_padrao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comboproduto',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='comboproduto',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='restaurante',
        ),
        migrations.RemoveField(
            model_name='itemalteracao',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='itemalteracao',
            name='item',
        ),
        migrations.RemoveField(
            model_name='produtoingrediente',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='produtoingrediente',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='visivel',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='visivel',
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.DeleteModel(
            name='ComboProduto',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='ItemAlteracao',
        ),
        migrations.DeleteModel(
            name='ProdutoIngrediente',
        ),
    ]
