# Generated by Django 4.2.1 on 2023-05-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0020_produtoparteproduto_remove_comboproduto_combo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoparteproduto',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem_cliente.produto'),
        ),
        migrations.AlterField(
            model_name='produtoparteproduto',
            name='produto_parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_partes', to='totem_cliente.produto'),
        ),
    ]
