# Generated by Django 4.2.1 on 2023-05-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0021_alter_produtoparteproduto_produto_pai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
