# Generated by Django 4.2.1 on 2023-05-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0021_remove_comboproduto_combo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagem',
        ),
    ]
