# Generated by Django 4.2.1 on 2023-05-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0023_alter_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
    ]
