# Generated by Django 4.2.1 on 2023-05-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0023_alter_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoparteproduto',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='totem_cliente.produto'),
        ),
    ]
