# Generated by Django 4.2.1 on 2023-05-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0024_remove_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='nome_cliente',
        ),
    ]
