# Generated by Django 4.2.1 on 2023-05-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0025_alter_produtoparteproduto_produto_pai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemParteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('padrao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('item_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pais', to='totem_cliente.itempedido')),
                ('item_parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_partes', to='totem_cliente.itempedido')),
            ],
        ),
    ]
