# Generated by Django 4.2.1 on 2023-05-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0026_itemparteitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemparteitem',
            old_name='item_pai',
            new_name='item_principal',
        ),
        migrations.RenameField(
            model_name='produtoparteproduto',
            old_name='produto_pai',
            new_name='produto_principal',
        ),
        migrations.RenameField(
            model_name='produtoparteproduto',
            old_name='quantidade',
            new_name='quantidade_padrao',
        ),
        migrations.AddField(
            model_name='produtoparteproduto',
            name='quantidade_maxima',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produtoparteproduto',
            name='quantidade_minima',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
