# Generated by Django 4.2.1 on 2023-05-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem_cliente', '0028_remove_itemparteitem_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='parte',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ItemParteItem',
        ),
    ]
